name: kenya_economic_weather

version: "1.0.0"

config-version: 2

profile: kenya_economic_weather

model-paths:
  - models

test-paths:
  - tests

models:
  kenya_economic_weather:
    staging:
      +materialized: view