FROM python:3.12-slim

WORKDIR /usr/app

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.9.3 \
    dbt-postgres==1.9.1

ENTRYPOINT ["dbt"]